name: github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo (extended)
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Setup Node (for Dart Sass)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dart Sass (local)
        run: |
          npm init -y
          npm i --save-dev sass

      - name: Tell Hugo where Sass is
        run: echo "HUGO_DART_SASS=$(pwd)/node_modules/.bin/sass" >> $GITHUB_ENV

      - name: Verify Sass
        run: |
          echo "$HUGO_DART_SASS"
          $HUGO_DART_SASS --version

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public